### ISSUE TITLE
the data type "meg"  should be added to the directory structure. 

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/data-streamer#18] opened 2018-03-28 11:59 UTC
The directory structure should be 
sub-xxx/ses-yyy/type/datafiles
where type=meg

in our case it happens to be that yyy=meg01, but in the MEG session multiple data types could be recorded (e.g. behavioral log files, eye tracker data), which would go in different type-specific directories under the same session.

this relates to line
https://github.com/Donders-Institute/data-streamer/blob/9fdfd0ec21cdd42dab94172baddd77af73fd548f/docker/streamer/lib/modalityMEG.js#L190

**Comment by robertoostenveld** [comment] 2018-03-28 12:04
Although this was discussed and agreed upon in the MEG meeting (2 weeks back), not all MEG users will already be aware of it. I suggest that @jesask informs the researchers that are in the middle of a project and that still have new data streaming in.

**Comment by hurngchunlee** [comment] 2018-03-28 12:22
@robertoostenveld Am I right that we still keep the yyy to be meg01, but add one additional subdirectory "meg"?

The end result would be, e.g.

raw/sub-001/ses-meg01/meg/sub2ses3_3018032.01_20180328_01.ds

Correct?

**Comment by hurngchunlee** [comment] 2018-03-28 12:33
@marcelzwiers should this apply to MRI dataset as well?

**Comment by robertoostenveld** [comment] 2018-03-28 12:39
No. 

For MRI there is already the scan type (or whatever it is called) in between. Like "002-t1_mprage_sag”. The idea is that for further compliance those should be renamed to one of the BIDS data types, like “anat”, “func” or “dti”. (And of course the files inside should be converted from DICOM to NIFTI, but the raw directory only has to be BIDS-like, not fully compliant). So the directory depth for automatically streamed MRI data is fine as is.

**Comment by jesask** [comment] 2018-03-28 12:44
So if I understand correctly, only the 'type' folder is added to the structure in case of MEG data?
so raw/sub-01/ses-meg01/meg/meg.ds instead of raw/sub-01/ses-meg01/meg.ds?

so for MEG data, log files, edf files etc. will have to go into the 'raw' structure, whereas these additional files are not added into the mri 'raw' structure but added as a separate 'raw data' folder?

**Comment by hurngchunlee** [comment] 2018-03-28 18:06
code has been changed and deployed to the production.  It should apply immediately to the next MEG dataset.

I also changed the parsing of the subject and session id/name from the dataset name.  Hereafter is the new regular expression:

```javascript
        var subses_regex = new RegExp("^.*sub[j]{0,1}(\\S*)ses[s]{0,1}(\\S*)_.*$");
```

It should now capable to deal with more variations from the expected pattern.

@robertoostenveld and @jesask please check with the MEG user to see if it works as expected.

**Comment by hurngchunlee** [comment] 2019-08-16 09:08
I assume the issue is resolved.  Closing it by now.

**Closed by hurngchunlee** 2019-08-16 09:08 UTC
